[package]
name = "rust_udemy_beginner"
version = "0.1.0"
authors = ["Tam <npt.dc@outlook.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.7.3"
